name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image: ['docker.io/ndomi/fastapi:latest', 'another/image:tag', 'yet/another/image:tag']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: ${{ matrix.container_image }}
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results-${{ matrix.container_image }}.sarif"
          # exit-code: "0"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          severity: "CRITICAL,HIGH"

      - name: Create Gist
        id: gist
        uses: ghes/actions/github-gist-action@v2
        with:
          filename: "trivy-results-${{ matrix.container_image }}.sarif"
          gistname: "trivy-results-${{ matrix.container_image }}.sarif"
          description: Trivy vulnerability scan report
          public: true
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}    

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          Trivy vulnerability scan report: ${{ steps.gist.outputs.gist_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()